#+TITLE: QUI - Quick UI
#+DATE: 2020-07-16
#+STARTUP: showall

QUI is a quick and simple user interface library for C.

The library is meant to be extremely simple to drop into a project and
get a quick UI up and running for prototyping, visualizing, and/or
debugging. It isn't a desktop environment or a full featured widget
library. Use it when you need basic windows, drawing primitives, and
maybe a button or two.

The only documentation is the README. The README contains everything
you'll ever need when using QUI: how to use it, how to build it, how
to hack it, a tutorial, and a complete reference.

** Library conventions

Types are prefixed with =Qu=. There are opaque object references
(QuApp, QuWindow, QuButton, etc.) and small structs (QuRect, QuPoint,
QuRGBA, etc.).

Opaque references are malloc'd with a constructor function that ends
with =A= and you're responsible for freeing the returned reference.
Small structs are created on the stack and no manual memory management
is needed, they end with a =S=.

#+begin_src C
QuApp app = QuAppA(); // A = allocate on the heap
QuRect rect = QuRectS(); // S = staticly allocate or allocate on the stack
#+end_src

Types are names such that they follow the form PrefixType where Qu is
the prefix and type is App, Window, View, etc.

Functions begin with the lowercase type name without the prefix and
/always/ take an object of the named type as the first argument.
